/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cn.yongye.nativeshell;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int colorAccent=0x7f050002;
        public static final int colorPrimary=0x7f050000;
        public static final int colorPrimaryDark=0x7f050001;
    }
    public static final class drawable {
        public static final int ic_launcher_background=0x7f020000;
        public static final int ic_launcher_foreground=0x7f020001;
        public static final int ic_launcher_foreground_1=0x7f020002;
    }
    public static final class layout {
        public static final int activity_main=0x7f040000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
        public static final int ic_launcher_round=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
    }
}
